// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $city_city from "./routes/city/city.tsx";
import * as $dog_dog from "./routes/dog/dog.tsx";
import * as $index from "./routes/index.tsx";
import * as $searchCity_search from "./routes/searchCity/search.tsx";
import * as $searchDog_searchDog from "./routes/searchDog/searchDog.tsx";
import * as $types from "./routes/types.ts";
import * as $user_randoUser from "./routes/user/randoUser.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/city/city.tsx": $city_city,
    "./routes/dog/dog.tsx": $dog_dog,
    "./routes/index.tsx": $index,
    "./routes/searchCity/search.tsx": $searchCity_search,
    "./routes/searchDog/searchDog.tsx": $searchDog_searchDog,
    "./routes/types.ts": $types,
    "./routes/user/randoUser.tsx": $user_randoUser,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
